baseUrl: https://www.7onn.dev
languageCode: en-us
title: "ğŸ“œğŸ§™â€â™‚ï¸ tom's blog"
theme: hugo-tania
enableEmoji: true
privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
menu:
  header:
  - name: Blog
    url: /
  - name: About
    url: /about/
  footer:
  - name: PGP
    url: /tom.asc
  - name: RSS
    url: /index.xml
markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true
params:
  #titleEmoji: 'ğŸ“œ'
  mainSections:
  - post
  socialOptions:
    github: https://github.com/7onn
    linkedin: https://www.linkedin.com/in/7onn/
    twitter: https://twitter.com/_7onn_
